// Database types - will be auto-generated by Supabase CLI
// For now, using placeholder types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 
  | 'tier1' 
  | 'tier2_officer' 
  | 'tier2_registrar' 
  | 'company_admin' 
  | 'company_manager' 
  | 'company_user' 
  | 'auditor' 
  | 'system_admin' 
  | 'vendor'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          company_id: string | null
          role: UserRole
          avatar_url: string | null
          timezone: string
          language: string
          notification_preferences: Json | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          company_id?: string | null
          role: UserRole
          avatar_url?: string | null
          timezone?: string
          language?: string
          notification_preferences?: Json | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          company_id?: string | null
          role?: UserRole
          avatar_url?: string | null
          timezone?: string
          language?: string
          notification_preferences?: Json | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      companies: {
        Row: {
          id: string
          name: string
          registration_number: string
          company_type: 'ipc' | 'wholesaler'
          address: string | null
          contact_email: string | null
          contact_phone: string | null
          is_active: boolean
          suspended_at: string | null
          suspended_by: string | null
          suspended_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          registration_number: string
          company_type: 'ipc' | 'wholesaler'
          address?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          registration_number?: string
          company_type?: 'ipc' | 'wholesaler'
          address?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          is_active?: boolean
          suspended_at?: string | null
          suspended_by?: string | null
          suspended_reason?: string | null
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string
          link: string | null
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          message: string
          link?: string | null
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          is_read?: boolean
          read_at?: string | null
        }
      }
      system_config: {
        Row: {
          id: string
          module_name: 'rmm' | 'vci' | 'ecs' | 'cmc'
          is_active: boolean
          activated_at: string | null
          activated_by: string | null
          config_data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          module_name: 'rmm' | 'vci' | 'ecs' | 'cmc'
          is_active?: boolean
          activated_at?: string | null
          activated_by?: string | null
          config_data?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          is_active?: boolean
          activated_at?: string | null
          activated_by?: string | null
          config_data?: Json
          updated_at?: string
        }
      }
    }
    Functions: {
      shared_get_user_permissions: {
        Args: { p_user_id?: string }
        Returns: Json
      }
      shared_check_module_active: {
        Args: { p_module_name: string }
        Returns: boolean
      }
      shared_create_notification: {
        Args: {
          p_user_id: string
          p_type: string
          p_title: string
          p_message: string
          p_link?: string
        }
        Returns: string
      }
      shared_mark_notification_read: {
        Args: { p_notification_id: string }
        Returns: boolean
      }
      shared_get_unread_notification_count: {
        Args: Record<string, never>
        Returns: number
      }
    }
  }
}
